void *memset(void *ptr,int value,unsigned long long int size);
asm(".text");
asm(".globl memset");
asm("memset:");
asm("push %rdi");
asm("push %rsi");
asm("push %rdx");
asm("mov %sil,%al");
asm("cmp $8,%rdx");
asm("jb _memset_X1");
asm("mov %al,%ah");
asm("mov %dil,%al");
asm("xchg %al,%ah");
asm("and $7,%ah");
asm("je _memset_X3");
asm("or $0xf8,%ah");
asm("mov %al,(%rdi)");
asm("inc %rdi");
asm("dec %rdx");
asm("inc %ah");
asm("je _memset_X3");
asm("mov %al,(%rdi)");
asm("inc %rdi");
asm("dec %rdx");
asm("inc %ah");
asm("je _memset_X3");
asm("mov %al,(%rdi)");
asm("inc %rdi");
asm("dec %rdx");
asm("inc %ah");
asm("je _memset_X3");
asm("mov %al,(%rdi)");
asm("inc %rdi");
asm("dec %rdx");
asm("inc %ah");
asm("je _memset_X3");
asm("mov %al,(%rdi)");
asm("inc %rdi");
asm("dec %rdx");
asm("inc %ah");
asm("je _memset_X3");
asm("mov %al,(%rdi)");
asm("inc %rdi");
asm("dec %rdx");
asm("inc %ah");
asm("je _memset_X3");
asm("mov %al,(%rdi)");
asm("inc %rdi");
asm("dec %rdx");
asm("_memset_X3:");
asm("movzbl %al,%eax");
asm("mov %rdx,%rsi");
asm("movabs $0x101010101010101,%rdx");
asm("mul %rdx");
asm("mov %rsi,%rdx");
asm("_memset_X4:");
asm("sub $64,%rdx");
asm("jb _memset_X5");
asm("mov %rax,(%rdi)");
asm("mov %rax,8(%rdi)");
asm("mov %rax,16(%rdi)");
asm("mov %rax,24(%rdi)");
asm("mov %rax,32(%rdi)");
asm("mov %rax,40(%rdi)");
asm("mov %rax,48(%rdi)");
asm("mov %rax,56(%rdi)");
asm("lea 64(%rdi),%rdi");
asm("jmp _memset_X4");
asm("_memset_X5:");
asm("test $32,%dl");
asm("je _memset_Y1");
asm("mov %rax,(%rdi)");
asm("mov %rax,8(%rdi)");
asm("mov %rax,16(%rdi)");
asm("mov %rax,24(%rdi)");
asm("lea 32(%rdi),%rdi");
asm("_memset_Y1:");
asm("test $16,%dl");
asm("je _memset_Y2");
asm("mov %rax,(%rdi)");
asm("mov %rax,8(%rdi)");
asm("lea 16(%rdi),%rdi");
asm("_memset_Y2:");
asm("test $8,%dl");
asm("je _memset_Y3");
asm("mov %rax,(%rdi)");
asm("lea 8(%rdi),%rdi");
asm("_memset_Y3:");
asm("and $7,%dl");
asm("_memset_X1:");
asm("test %dl,%dl");
asm("je _memset_X2");
asm("mov %al,(%rdi)");
asm("inc %rdi");
asm("dec %dl");
asm("je _memset_X2");
asm("mov %al,(%rdi)");
asm("inc %rdi");
asm("dec %dl");
asm("je _memset_X2");
asm("mov %al,(%rdi)");
asm("inc %rdi");
asm("dec %dl");
asm("je _memset_X2");
asm("mov %al,(%rdi)");
asm("inc %rdi");
asm("dec %dl");
asm("je _memset_X2");
asm("mov %al,(%rdi)");
asm("inc %rdi");
asm("dec %dl");
asm("je _memset_X2");
asm("mov %al,(%rdi)");
asm("inc %rdi");
asm("dec %dl");
asm("je _memset_X2");
asm("mov %al,(%rdi)");
asm("inc %rdi");
asm("_memset_X2:");
asm("pop %rdx");
asm("pop %rsi");
asm("pop %rdi");
asm("mov %rdi,%rax");
asm("ret");
void *memcpy(void *dst,const void *src,unsigned long long int size);
asm(".text");
asm(".globl memcpy");
asm("memcpy:");
asm("_memcpy_X2:");
asm("sub $64,%rdx");
asm("jb _memcpy_X1");
asm("movups (%rsi),%xmm0");
asm("movups 16(%rsi),%xmm1");
asm("movups 32(%rsi),%xmm2");
asm("movups 48(%rsi),%xmm3");
asm("movups %xmm0,(%rdi)");
asm("movups %xmm1,16(%rdi)");
asm("movups %xmm2,32(%rdi)");
asm("movups %xmm3,48(%rdi)");
asm("lea 64(%rdi),%rdi");
asm("lea 64(%rsi),%rsi");
asm("jmp _memcpy_X2");
asm("_memcpy_X1:");
asm("test $32,%dl");
asm("je _memcpy_X3");
asm("movups (%rsi),%xmm0");
asm("movups 16(%rsi),%xmm1");
asm("movups %xmm0,(%rdi)");
asm("movups %xmm1,16(%rdi)");
asm("lea 32(%rdi),%rdi");
asm("lea 32(%rsi),%rsi");
asm("_memcpy_X3:");
asm("test $16,%dl");
asm("je _memcpy_X4");
asm("movups (%rsi),%xmm0");
asm("movups %xmm0,(%rdi)");
asm("lea 16(%rdi),%rdi");
asm("lea 16(%rsi),%rsi");
asm("_memcpy_X4:");
asm("test $8,%dl");
asm("je _memcpy_X5");
asm("mov (%rsi),%rax");
asm("mov %rax,(%rdi)");
asm("lea 8(%rdi),%rdi");
asm("lea 8(%rsi),%rsi");
asm("_memcpy_X5:");
asm("test $4,%dl");
asm("je _memcpy_X6");
asm("mov (%rsi),%eax");
asm("mov %eax,(%rdi)");
asm("lea 4(%rdi),%rdi");
asm("lea 4(%rsi),%rsi");
asm("_memcpy_X6:");
asm("test $2,%dl");
asm("je _memcpy_X7");
asm("mov (%rsi),%ax");
asm("mov %ax,(%rdi)");
asm("lea 2(%rdi),%rdi");
asm("lea 2(%rsi),%rsi");
asm("_memcpy_X7:");
asm("test $1,%dl");
asm("je _memcpy_X8");
asm("mov (%rsi),%al");
asm("mov %al,(%rdi)");
asm("_memcpy_X8:");
asm("ret");
unsigned long long int strlen(const char *str);
asm(".text");
asm(".globl strlen");
asm("strlen:");
asm("mov %rdi,%rax");
asm("_strlen_X2:");
asm("testb $0xff,(%rax)");
asm("je _strlen_X1");
asm("inc %rax");
asm("testb $0xff,(%rax)");
asm("je _strlen_X1");
asm("inc %rax");
asm("testb $0xff,(%rax)");
asm("je _strlen_X1");
asm("inc %rax");
asm("testb $0xff,(%rax)");
asm("je _strlen_X1");
asm("inc %rax");
asm("testb $0xff,(%rax)");
asm("je _strlen_X1");
asm("inc %rax");
asm("testb $0xff,(%rax)");
asm("je _strlen_X1");
asm("inc %rax");
asm("testb $0xff,(%rax)");
asm("je _strlen_X1");
asm("inc %rax");
asm("testb $0xff,(%rax)");
asm("je _strlen_X1");
asm("inc %rax");
asm("jmp _strlen_X2");
asm("_strlen_X1:");
asm("sub %rdi,%rax");
asm("ret");
char *strcpy(char *dst,const char *src)
{
	int l=strlen(src);
	memcpy(dst,src,l+1);
	return dst;
}
char *strcat(char *dst,const char *src)
{
	unsigned long long int l1=strlen(src),l2=strlen(dst);
	memcpy(dst+l2,src,l1+1);
	return dst;
}
